# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('message', models.CharField(max_length=1000)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsender', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lreciever', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
