# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 10:24
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20170924_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
